[package]
  authors = []
  edition = "2021"
  name = "json_schema_nif"
  version = "0.1.1"

[lib]
  crate-type = ["cdylib", "lib"]
  name = "json_schema_nif"
  path = "src/lib.rs"

[dependencies]
  jsonschema = "0.17.1"
  log = "0.4.20"
  rustler = "0.30.0"
  serde_json = "1.0.108"
